feat: первая часть дипломного проекта
necron33rus/java-explore-with-me pull request #3
Opened 2023-09-12 13:18 UTC by necron33rus

2023-09-12 16:08 UTC, Frilock requested changes
Добрый день, написал ряд комментариев к вашей работе, жду новую версию

2023-09-12 16:08 UTC, Frilock commented on ewm-service/pom.xml
> +            <version>1.18.24</version>
Общий комментарий по pom файлам. Смотрите, у Вас многомодульный проект, так вот, хочется чтобы в приложении была одна точка добавления зависимостей. Такой обычно делают корневой pom файл. Там нужно сделать блок dependencyManager и добавлять те библиотеки которых нет в parent, а затем уже в других pom файлах подключать, но уже без указания версии. Кроме того, версии этих библиотек правильнее указывать в properties, поскольку pom файлы бывают довольно больших размеров и изменение версии может быть не такой простой задачей.

2023-09-12 16:08 UTC, Frilock commented on pom.xml
> +
Лишняя пустая строка

2023-09-12 16:08 UTC, Frilock commented on stat-service/server/src/main/java/ru/practicum/server/repository/StatisticsRepository.java
> +@Repository
Лишняя аннотация

2023-09-12 16:08 UTC, Frilock commented on stat-service/server/src/main/resources/schema.sql
> +    app       TEXT,
Когда создаете таблицы продумывайте размерность полей, вот например, для поля ip хватит и 50 символов, а для описания, конечно, этого будет мало. Кроме того, размер который вы укажите тут, нужно так же прописать в аннотации column в классах модели

2023-09-13 08:01 UTC, necron33rus commented on stat-service/server/src/main/java/ru/practicum/server/repository/StatisticsRepository.java
> +@Repository
done

2023-09-13 08:18 UTC, necron33rus commented on stat-service/server/src/main/resources/schema.sql
> +    app       TEXT,
done

2023-09-14 06:22 UTC, necron33rus commented on pom.xml
> +
done

2023-09-14 06:22 UTC, necron33rus commented on ewm-service/pom.xml
> +            <version>1.18.24</version>
вроде done

2023-09-14 11:15 UTC, Frilock approved these changes
Принято

2023-09-14 11:15 UTC, Frilock commented on pom.xml
>  	<properties>
пропертис лучше выше располагать

2023-09-14 11:15 UTC, Frilock commented on pom.xml
> +			<dependency>
По идее эта зависимость тут не нужна

2023-09-14 11:19 UTC, merged