feat: вторая часть дипломного проекта
necron33rus/java-explore-with-me pull request #4
Opened 2023-10-12 15:27 UTC by necron33rus

2023-10-13 15:01 UTC, Frilock requested changes
Добрый день, в целом особых замечаний нет, все в целом написано хорошо

2023-10-13 15:01 UTC, Frilock commented on stats/server/src/main/java/ru/practicum/ewm/stats/server/exception/ResponseError.java
> +
Лишняя пустая строка

2023-10-13 15:01 UTC, Frilock commented on stats/server/src/main/java/ru/practicum/ewm/stats/server/service/StatsServiceImpl.java
> +            stats = endpointHitRepository.findUniqueStats(start, end, uris);
Можно заменить на тернарное выражение, будет компактнее

2023-10-13 18:13 UTC, necron33rus commented on service/src/main/java/ru/practicum/ewm/service/category/controller/CategoriesPublicController.java
> +        log.info("Поступил запрос на получение списка категорий.");
done

2023-10-13 18:14 UTC, necron33rus commented on service/src/main/java/ru/practicum/ewm/service/category/repository/CategoryRepository.java
> +@Repository
done

2023-10-13 18:18 UTC, necron33rus commented on service/src/main/java/ru/practicum/ewm/service/compilation/controller/CompilationPublicController.java
> +                                       @Valid @RequestParam(required = false, defaultValue = "0") @Min(0) int from,
убрал

2023-10-13 18:18 UTC, necron33rus commented on service/src/main/java/ru/practicum/ewm/service/compilation/repository/CompilationRepository.java
> +@Repository
done

2023-10-13 18:19 UTC, necron33rus commented on service/src/main/java/ru/practicum/ewm/service/compilation/service/CompilationServiceImpl.java
> +@Slf4j
done

2023-10-13 18:21 UTC, necron33rus commented on service/src/main/java/ru/practicum/ewm/service/compilation/service/CompilationServiceImpl.java
> +        List<Event> events = dto.getEvents() != null && !dto.getEvents().isEmpty() ?
надо про нее почитать побольше
done

2023-10-13 18:21 UTC, necron33rus commented on service/src/main/java/ru/practicum/ewm/service/constant/DateTimeFormat.java
> +    public DateTimeFormat() {
done

2023-10-13 18:26 UTC, necron33rus commented on service/src/main/java/ru/practicum/ewm/service/event/model/Event.java
> +    @Column(name = "event_annotation", nullable = false)
done

2023-10-13 18:28 UTC, necron33rus commented on service/src/main/java/ru/practicum/ewm/service/event/repository/EventRepository.java
> +@Repository
done

2023-10-13 18:28 UTC, necron33rus commented on service/src/main/java/ru/practicum/ewm/service/event/repository/LocationRepository.java
> +@Repository
done

2023-10-13 18:31 UTC, necron33rus commented on service/src/main/java/ru/practicum/ewm/service/event/service/EventPrivateServiceImpl.java
> +        if (!(event.getState().equals(CANCELED) ||
done

2023-10-13 18:31 UTC, necron33rus commented on service/src/main/java/ru/practicum/ewm/service/participation/repository/ParticipationRequestRepository.java
> +@Repository
done

2023-10-13 18:32 UTC, necron33rus commented on service/src/main/java/ru/practicum/ewm/service/user/repository/UserRepository.java
> +@Repository
done

2023-10-13 18:33 UTC, necron33rus commented on stats/dto/src/main/java/ru/practicum/ewm/stats/dto/util/DateTimeFormat.java
> +    public DateTimeFormat() {
done

2023-10-13 18:33 UTC, necron33rus commented on stats/server/src/main/java/ru/practicum/ewm/stats/server/exception/ResponseError.java
> +
done

2023-10-13 18:35 UTC, necron33rus commented on stats/server/src/main/java/ru/practicum/ewm/stats/server/service/StatsServiceImpl.java
> +            stats = endpointHitRepository.findUniqueStats(start, end, uris);
done

2023-10-13 18:36 UTC, necron33rus commented on service/src/main/java/ru/practicum/ewm/service/user/service/UserServiceImpl.java
> +        if (ids != null && !ids.isEmpty()) {
done

2023-10-13 18:42 UTC, necron33rus commented on pom.xml
> +		<module>stats</module>
запутался в помниках(( 
поменял на нормальыне

2023-10-13 18:43 UTC, necron33rus commented on service/src/main/java/ru/practicum/ewm/service/event/service/EventAdminServiceImpl.java
> +            if (updateEventAdminRequest.getStateAction().equals(PUBLISH_EVENT)
done

2023-10-14 06:45 UTC, Frilock approved these changes
Принято, в целом все хорошо

2023-10-14 15:30 UTC, merged